### PR TITLE
Call signal receivers in the order they were first registered

### PR DESCRIPTION
**Pull request by gilpinheiro**
## Problem statement:

I'm using pelican, and have a set of plugins that I'd like to apply -- pelican uses blinker as its primary extension mechanism to handle lifecycle hooks.

Since one plugin relies on another (or at least can recognize and make use of their results), they need to be applied in a set order. Ideally, they should be applied in the order specified in plugin load order. Otherwise they are applied in random or inconsistent order. 

The current system doesn't guarantee ordering.

## This change set

To make this change required the use of an ordered set and ordered dictionary.

* I've added a dependency to the project for python versions older than 2.7 to polyfill collections.OrderedDict (handled in setup.py and proxied via _utilities)

* I've added an implementation of orderedsets, the implementation has broad support across python
versions, but indicates it should work back to only python 2.6 (would require a bump in minimum version)

All signals are connected via ordered variants of the existing structures.

Dispatch is done in an ordered fashion, with receivers being notified in the order the were first added (regardless of how many times they hold connections via different sender filters)

## Desirable outcomes

I think this is a mainline-appropriate feature. Since the library specified arbitrary order, this change should not break any existing code. Adding a strong/predictable ordering does have predictability benefits and should reduce phantom bugs that occur only occasionally because of random ordering.

See the comment on the last commit for a potential weakness of this implementation. If you have any general feedback or insight into why it would be desirable to keep the unordered implementation, I'm interested.

Whether or not this is pulled into mainline, I would like this feature for my own use, if anyone else ends up using this fork and ends up here - I welcome any additional requests or fixes you might find.

### CODE REVIEW

**Comment by Leboudin** [comment]
@gilpinheiro Hi! Clearly that jek hasnt been seen for years, I do suggest you make a fork yourself, or contact the author or whatever if you are still working on this.

**Comment by jek** [comment]
Known-order is at odds with the philosophy and practice of Blinker signals in general, so it's unlikely that I would merge any ordering PR into the base library.  However I'm not opposed to making changes that would make it more convenient to implement ordered signals oneself in their own codebase.

**Comment by gilpinheiro** [comment]
Thanks for the review. I use my branch for my own projects, and if there isn't pressing need from others, than I'm content to keep it that way. 

If others find this pull request or my git branch via search, and think it is useful, just send me message. Maybe I'll come back and make ordered mode an __init__ option, which I think would meet jek's requirements.

**Comment by jek** [comment]
If there was a hook to intercept and modify the stream of receivers that `send` uses, then this sort of feature could be implemented by listening to the signal's own `receiver_connected` signal to handle bookkeeping and then fiddling with the ordering at `send` time.

There's a branch with a `receiver_adapter` that allows interception of individual receivers. Perhaps that could be reworked into a hook that intercepts all the receiver stream instead, and thus catch a wide swath of use cases in one shot.

**Comment by sullyfischer** [comment]
I just googled for this exact topic. If it doesn't break anything, please merge it.

**Comment by pawamoy** [comment]
(For interested readers: I found a relatively short way to implement this within your own code, see https://github.com/pallets-eco/blinker/discussions/105)

**Comment by pgjones** [comment]
Closed in favor of #116

**Pull request closed without merging**
